"""empty message

Revision ID: 4ca9b03062bb
Revises: 
Create Date: 2025-12-17 21:26:24.905119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca9b03062bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testcase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_to_show', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('expected_output_to_show', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testcase', schema=None) as batch_op:
        batch_op.drop_column('expected_output_to_show')
        batch_op.drop_column('input_to_show')

    # ### end Alembic commands ###
