"""empty message

Revision ID: 5df816c203c6
Revises: e1a04120e1db
Create Date: 2025-12-15 16:25:39.382814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df816c203c6'
down_revision = 'e1a04120e1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testcases_executed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_testcases', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_answer', schema=None) as batch_op:
        batch_op.drop_column('total_testcases')
        batch_op.drop_column('testcases_executed')

    # ### end Alembic commands ###
