"""empty message

Revision ID: 95b30a10bb79
Revises: eb22d84c857f
Create Date: 2025-12-17 00:01:42.035968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95b30a10bb79'
down_revision = 'eb22d84c857f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_complexity', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('space_complexity', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_answer', schema=None) as batch_op:
        batch_op.drop_column('space_complexity')
        batch_op.drop_column('time_complexity')

    # ### end Alembic commands ###
