"""message

Revision ID: e1a04120e1db
Revises: 
Create Date: 2025-12-11 13:04:42.685834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a04120e1db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_exec_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_exec_memory', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('language_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('language_name')
        batch_op.drop_column('total_exec_memory')
        batch_op.drop_column('total_exec_time')

    # ### end Alembic commands ###
