"""added few cols in problem table

Revision ID: eb22d84c857f
Revises: 5df816c203c6
Create Date: 2025-12-16 12:01:31.585530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb22d84c857f'
down_revision = '5df816c203c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_submissions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_submissions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('acceptance_rate', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('acceptance_rate')
        batch_op.drop_column('total_submissions')
        batch_op.drop_column('accepted_submissions')

    
    # ### end Alembic commands ###
